# Site settings
title: "CWA Resume"
description: "My Resume and CV."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "C.W.A. Coder with attitude"
resume_title:                   "C.W.A. Resume"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "cwa.coder.with.attitude@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+49 151 21 366 110"
resume_contact_address:         "Margeritenstr. 14, 61118 Bad Vilbel"

resume_header_contact_info:     "Margeritenstr. 14, 61118 Bad Vilbel • 0151 21 366 110 • cwa.coder.with.attitude@gmail.com"
display_header_contact_info:    "false"

#resume_header_intro: "<p>This is the executive summary. You should write a few brief, concise, and meaningful sentences about yourself from a professional context, and your immediate career goals. Make the length appropriate for your needs, but keep it brief and concise</p>"
resume_header_intro: "<p>Software is in my DNA. I like to design and write code that solves a real problem. Whether it be a small piece of code or a fragment in a large scale enterprise application.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       false #true
resume_section_projects:        true #true
resume_section_skills:          true
resume_section_recognition:     false #true
resume_section_links:           false #true
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://cwacoderwithattitude.github.io"
  resume_twitter_url:           "http://twitter.com/JavaVolker"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
