# Create a Jekyll container for GitHub Pages
# See this for current supported versions: https://pages.github.com/versions/
FROM ruby:3.3

# Update the Ruby bundler
RUN gem update bundler 

# Install Jekyll
RUN gem install bundler jekyll 
RUN git config --global user.name "CoderWithAttitude"
RUN git config --global user.email "CWA.CoderWithAttitude@gmail.com"