FROM bretfisher/jekyll-serve

CMD ["/bin/bash"]
#CMD ["jekyll", "build", "--watch", "--incremental", "--destination", "/srv/jekyll/_site"]
#CMD ["jekyll", "serve", "--host", "0.0.0.0", "--port", "4000", "--watch"]